AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy cloudfront

Parameters:
  s3Stack:
    Description: Nombre del stack con el bucket s3 para el sitio web
    Type: String
  certificateArn:
    Description: arn del certificado del DNS
    Type: String
  CustomDomainName:
    Description: arn del certificado del DNS
    Type: String
  HostedZoneIdValue:
    Description: Id de la Zona alojada
    Type: String

Resources:
  myDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: "http2"
        Comment: Distribution para my-aws-stack
        Aliases:
          - !Ref CustomDomainName
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: false
          TargetOriginId: widgetOrigin
          ViewerProtocolPolicy: "redirect-to-https"
        Enabled: true
        IPV6Enabled: true
        DefaultRootObject: "index.html"
        Origins:
          - DomainName: { "Fn::ImportValue": !Sub "${s3Stack}-domain" }
            Id: widgetOrigin
            S3OriginConfig:
              OriginAccessIdentity:
                !Join [
                  "",
                  [
                    "origin-access-identity/cloudfront/",
                    { "Fn::ImportValue": !Sub "${s3Stack}-cloudFrontUser" },
                  ],
                ]
        PriceClass: "PriceClass_All"
        ViewerCertificate:
          AcmCertificateArn: !Ref certificateArn
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"

  myDNS:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: !Red HostedZoneIdValue
      RecordSets:
        - Name: !Ref CustomDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt
              - myDistribution
              - DomainName
